---
kind: ConfigMap
apiVersion: v1
metadata:
  name: typo-fix
immutable: false
data:
  repos: |-
    https://github.com/rh-ai-kickstart/custom-workbench-images-examples.git
  prompt: |-
    Please look at the markdown files in the repository and then correct any typos that you find. 
    If there are references to other files or other sections of the README, turn them into links.
        
    If you find any reference to "Kickstart", replace it with the full name: "AI Kickstart"

    After that, please push the changes to GitHub and open a pull request. 
    Please create a meaningful branch name that describes the changes. 
    If a pull request template exists in the repository, please follow it when creating the PR description.
