---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openhands-issue-resolver-pipeline
spec:
  description: Simple OpenHands pipeline that processes specified repositories
  params:
    # Standard pipeline parameters
    - name: repo-url
      type: string
      description: Repository URL to process
      default: "https://github.com/RHRolun/test-openhands"
    - name: llm-model
      type: string
      description: LLM model to use
      default: "openai/qwen/qwen3-235b-a22b-07-25:free"
    - name: max-iterations
      type: string
      description: Maximum iterations for OpenHands
      default: "10"
    # Event context parameters
    - name: event-type
      type: string
      description: GitHub event type
      default: "issue"
    - name: repo-full-name
      type: string
      description: Repository full name (org/repo)
      default: "RHRolun/test-openhands"
    - name: username
      type: string
      description: Git username that owns the PAT
    - name: namespace
      type: string
      description: Namespace to run OpenHands
    - name: issue-number
      type: string
      description: Specific issue number to process
    - name: pvc-name
      type: string
      description: PVC name to use for session ID 
  workspaces:
    - name: workspace
      description: Shared workspace for processing
  tasks:
    - name: clone-repository
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines 
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: URL
          value: "$(params.repo-url)"
        - name: REVISION
          value: "main"
        - name: DELETE_EXISTING
          value: "true"
        - name: SSL_VERIFY
          value: "false"
    - name: openhands-issue-resolver
      taskRef:
        name: openhands-issue-resolver-2
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: llm-model
          value: $(params.llm-model)
        - name: max-iterations
          value: $(params.max-iterations)
        - name: event-type
          value: $(params.event-type)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: username
          value: $(params.username)
        - name: namespace
          value: openhands-pipeline
        - name: issue-number
          value: $(params.issue-number)
        - name: pvc-name
          value: $(params.pvc-name)
      runAfter:
        - clone-repository